export const SET_PRODUCT = "SET_PRODUCT";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const SET_COPY_ALL_PRODUCTS = "SET_COPY_ALL_PRODUCTS";
export const SET_FILTER_PRODUCTS = "SET_FILTER_PRODUCTS";
export const GET_PRODUCT_BY_NAME = "GET_PRODUCT_BY_NAME";
export const SET_PRODUCT_DETAIL = "SET_PRODUCT_DETAIL";
export const GET_PRODUCTS_DEFAULT = "GET_PRODUCTS_DEFAULT";

export const POST_PRODUCT = "POST_PRODUCT";

export const TOTAL_PAGES = "TOTAL_PAGES";

export const URL_BASE_PRODUCTS = "http://localhost:3001/products";

export const GET_CATEGORIES = " GET_CATEGORIES";
export const GET_CATEGORY = "GET_CATEGORY";
export const ORDER = "ORDER";

//CONSTANTS SUPPLIERS
export const GET_SUPPLIERS = "GET_SUPPLIERS";

//CONSTANTS CATEGORIES
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
