export const SET_PRODUCT = "SET_PRODUCT";

export const SET_COPY_ALL_PRODUCTS = "SET_COPY_ALL_PRODUCTS";
export const SET_FILTER_PRODUCTS = "SET_FILTER_PRODUCTS";

export const SET_PRODUCT_DETAIL = "SET_PRODUCT_DETAIL";
export const GET_PRODUCTS_DEFAULT = "GET_PRODUCTS_DEFAULT";
export const GET_PRODUCTS_BY_FILTERS = "GET_PRODUCTS_BY_FILTERS";
export const GET_ALL_PRODUCTS_NAMES = "GET_ALL_PRODUCTS_NAMES";
export const GET_ACCESORIES = "GET_ACCESORIES";

export const POST_PRODUCT = "POST_PRODUCT";

export const TOTAL_PAGES = "TOTAL_PAGES";
/* eslint-disable */
export const URL_BASE = process.env.REACT_APP_API;

export const GET_CATEGORIES = " GET_CATEGORIES";

//CONSTANTS SUPPLIERS
export const GET_SUPPLIERS = "GET_SUPPLIERS";

//CONSTANTS CATEGORIES
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const PRODUCTS_CONTROLLER = "PRODUCTS_CONTROLLER";
