import React from "react";
import AdminTopbar from "../../Components/AdminTopbar/AdminTopbar";
import { StyledAdminPanel } from "./styledAdminPanel";

export default function AdminPanel() {
  return (
    <StyledAdminPanel>
      <AdminTopbar />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
      test<br />
    </StyledAdminPanel>
  );
}
